package markdiff

import (
	"errors"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"testing"

	"github.com/aymanbagabas/go-udiff"
)

// UpdateEnv is the environment variable that, when set to a true value,
// rewrites documents instead of comparing them.
const UpdateEnv = "MARKDIFF_UPDATE"

// The flag has a package-qualified name so it never collides with the
// common -update flag registered by other golden-file helpers. That flag is
// still honored when present; see [updating].
var updateFlag = flag.Bool("markdiff.update", false, "rewrite markdiff documents with the current test output")

// DefaultDir is the directory, relative to the package under test, where
// documents are stored by default.
var DefaultDir = filepath.Join("testdata", "markdiff")

// Doc is a Markdown document describing the behavior exercised by a test.
// Create one with [New]; it is checked automatically when the test ends.
type Doc struct {
	Body

	title   string
	summary string
	path    string
	update  *bool
}

// Option configures a [Doc].
type Option func(*Doc)

// WithPath stores the document at path instead of the location derived from
// the test name. Relative paths are relative to the package directory.
func WithPath(path string) Option {
	return func(d *Doc) { d.path = path }
}

// withUpdate forces update mode on or off, regardless of flags. It exists
// for testing this package.
func withUpdate(update bool) Option {
	return func(d *Doc) { d.update = &update }
}

// New starts a document for the running test. The title becomes the
// top-level heading, and the summary, which must not be empty, introduces
// the system under test to the reader.
//
// The document is compared with (or, in update mode, written to) its file
// when the test and all of its subtests complete.
func New(tb testing.TB, title, summary string, opts ...Option) *Doc {
	tb.Helper()

	d := &Doc{
		Body:    Body{tb: tb, level: 1},
		title:   strings.TrimSpace(title),
		summary: strings.TrimSpace(summary),
		path:    PathFor(tb.Name()),
	}
	for _, opt := range opts {
		opt(d)
	}

	if d.title == "" {
		tb.Fatalf("markdiff: document needs a title")
	}
	if d.summary == "" {
		tb.Fatalf("markdiff: document %q needs a summary explaining the system under test", d.title)
	}
	if err := claimPath(d.path, tb.Name()); err != nil {
		tb.Fatalf("markdiff: %v", err)
	}

	tb.Cleanup(func() {
		releasePath(d.path)
		d.check()
	})
	return d
}

// Path returns the file the document is compared with.
func (d *Doc) Path() string {
	return d.path
}

// String renders the document as Markdown.
func (d *Doc) String() string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "<!-- Generated by %s using markdiff. Do not edit; rerun the test with -markdiff.update. -->\n\n", d.tb.Name())
	fmt.Fprintf(&sb, "# %s\n\n%s\n", d.title, d.summary)
	if s := d.render(); s != "" {
		sb.WriteString("\n")
		sb.WriteString(s)
	}
	return sb.String()
}

func (d *Doc) check() {
	tb := d.tb
	if tb.Failed() {
		tb.Logf("markdiff: not checking %s because the test failed", d.path)
		return
	}

	got := d.String()
	if d.updating() {
		if err := os.MkdirAll(filepath.Dir(d.path), 0o755); err != nil {
			tb.Errorf("markdiff: %v", err)
			return
		}
		if err := os.WriteFile(d.path, []byte(got), 0o644); err != nil {
			tb.Errorf("markdiff: %v", err)
		}
		return
	}

	raw, err := os.ReadFile(d.path)
	if errors.Is(err, fs.ErrNotExist) {
		tb.Errorf("markdiff: %s does not exist; rerun the test with -markdiff.update to create it", d.path)
		return
	}
	if err != nil {
		tb.Errorf("markdiff: %v", err)
		return
	}

	want := string(raw)
	// Git for Windows may check files out with CRLF line endings.
	if runtime.GOOS == "windows" {
		want = strings.ReplaceAll(want, "\r\n", "\n")
	}
	if diff := udiff.Unified(d.path, "test output", want, got); diff != "" {
		tb.Errorf("markdiff: %s does not match the test output; rerun the test with -markdiff.update if the change is intended:\n\n%s", d.path, diff)
	}
}

func (d *Doc) updating() bool {
	if d.update != nil {
		return *d.update
	}
	return updating()
}

// updating reports whether documents should be rewritten. Besides this
// package's own flag and environment variable, it honors a boolean -update
// flag registered by another package (such as x/exp/golden), so a single
// `go test -update` refreshes every kind of golden file.
func updating() bool {
	if *updateFlag {
		return true
	}
	if v, err := strconv.ParseBool(os.Getenv(UpdateEnv)); err == nil && v {
		return true
	}
	if f := flag.Lookup("update"); f != nil {
		if g, ok := f.Value.(flag.Getter); ok {
			if v, ok := g.Get().(bool); ok && v {
				return true
			}
		}
	}
	return false
}

// PathFor returns the default document path for a test name as reported by
// [testing.TB.Name]. Each subtest level becomes a directory.
func PathFor(testName string) string {
	parts := strings.Split(testName, "/")
	for i, p := range parts {
		parts[i] = sanitize(p)
	}
	return filepath.Join(DefaultDir, filepath.Join(parts...)) + ".md"
}

// sanitize keeps file names portable by replacing characters that are
// awkward or invalid on common filesystems.
func sanitize(s string) string {
	s = strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			return r
		case r == '-', r == '_', r == '.':
			return r
		default:
			return '_'
		}
	}, s)
	// Avoid names like "." or ".." that would escape the directory.
	if strings.Trim(s, ".") == "" {
		s = strings.ReplaceAll(s, ".", "_")
	}
	if s == "" {
		s = "_"
	}
	return s
}

var (
	pathsMu sync.Mutex
	paths   = map[string]string{}
)

// claimPath prevents two live documents from silently overwriting the same
// file, which would make the checked-in result depend on test ordering.
func claimPath(path, testName string) error {
	key, err := filepath.Abs(path)
	if err != nil {
		key = path
	}
	pathsMu.Lock()
	defer pathsMu.Unlock()
	if owner, ok := paths[key]; ok {
		return fmt.Errorf("%s is already used by a document in %s; use WithPath to give each document its own file", path, owner)
	}
	paths[key] = testName
	return nil
}

func releasePath(path string) {
	key, err := filepath.Abs(path)
	if err != nil {
		key = path
	}
	pathsMu.Lock()
	defer pathsMu.Unlock()
	delete(paths, key)
}
