package markdiff

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

// fakeTB records failures and cleanups so tests can observe how a Doc
// reports mismatches without failing the real test.
type fakeTB struct {
	testing.TB

	name     string
	errors   []string
	fatals   []string
	logs     []string
	cleanups []func()
}

func newFakeTB(t *testing.T, name string) *fakeTB {
	return &fakeTB{TB: t, name: name}
}

func (f *fakeTB) Name() string      { return f.name }
func (f *fakeTB) Helper()           {}
func (f *fakeTB) Failed() bool      { return len(f.errors)+len(f.fatals) > 0 }
func (f *fakeTB) Cleanup(fn func()) { f.cleanups = append(f.cleanups, fn) }
func (f *fakeTB) Logf(format string, a ...any) {
	f.logs = append(f.logs, fmt.Sprintf(format, a...))
}

func (f *fakeTB) Errorf(format string, a ...any) {
	f.errors = append(f.errors, fmt.Sprintf(format, a...))
}

func (f *fakeTB) Fatalf(format string, a ...any) {
	f.fatals = append(f.fatals, fmt.Sprintf(format, a...))
}

func (f *fakeTB) finish() {
	for i := len(f.cleanups) - 1; i >= 0; i-- {
		f.cleanups[i]()
	}
	f.cleanups = nil
}

// TestBuilder documents the Markdown produced by each builder method. It
// doubles as a rendered reference for test authors.
func TestBuilder(t *testing.T) {
	t.Parallel()

	doc := New(t, "markdiff builder reference",
		"This document is produced by markdiff itself. Each section shows "+
			"the Markdown rendered by one group of builder calls, "+
			"so changes to rendering show up here as a reviewable diff.")

	show := func(title, summary string, build func(*Body)) {
		sec := doc.Section(title, summary)
		inner := &Body{tb: t, level: sec.level}
		build(inner)
		sec.Text("Rendered Markdown:")
		sec.Code("markdown", inner.render())
	}

	show("Text", "Paragraphs are trimmed and separated by blank lines.", func(b *Body) {
		b.Text("  First paragraph.  ")
		b.Textf("Second paragraph with %d formatted value.", 1)
	})
	show("Code blocks", "The fence grows past any backtick run in the content, so fenced Markdown can itself be captured.", func(b *Body) {
		b.Code("go", "fmt.Println(\"hi\")")
		b.Code("markdown", "```sh\necho nested\n```\n")
	})
	show("JSON", "Values are encoded as indented JSON without HTML escaping.", func(b *Body) {
		b.JSON(map[string]any{"name": "<crush>", "tags": []string{"a", "b"}})
	})
	show("YAML", "Structured values can be captured in YAML when its compact, readable presentation helps reviewers.", func(b *Body) {
		b.YAML(map[string]any{"name": "<crush>", "tags": []string{"a", "b"}})
	})
	show("Lists", "Multi-line items stay inside their marker, and empty lists are explicit.", func(b *Body) {
		b.List("one", "two\ncontinued")
		b.NumberedList("first", "second")
		b.List()
	})
	show("Tables", "Short rows are padded; pipes and newlines in cells are escaped.", func(b *Body) {
		b.Table([]string{"Input", "Result"},
			[]string{"a|b", "line one\nline two"},
			[]string{"short"},
		)
	})
	show("Diffs", "Before and after text is shown as a unified diff, or a note when nothing changed.", func(b *Body) {
		b.Diff("alpha\nbeta\n", "alpha\ngamma\n")
		b.Diff("same", "same")
	})
	show("Quotes and details", "Quotes prefix every line; details wrap long supporting output.", func(b *Body) {
		b.Quote("Error: something went wrong\n\nTry again.")
		b.Details("Full log", func(d *Body) {
			d.Code("text", "line 1\nline 2")
		})
	})
	show("Nested sections", "Each nested section is one heading level deeper than its parent.", func(b *Body) {
		b.Section("Child", "A child section.").
			Section("Grandchild", "A grandchild section.")
	})
}

func TestPathFor(t *testing.T) {
	t.Parallel()

	doc := New(t, "Default document paths",
		"Documents are organized by test name below testdata/markdiff. "+
			"Subtests become directories, and characters that are awkward in "+
			"file names are replaced with underscores.")

	names := []string{
		"TestFoo",
		"TestFoo/bar",
		"TestFoo/with_spaces/#01",
		"TestFoo/a:b*c?",
		"TestFoo/..",
	}
	rows := make([][]string, 0, len(names))
	for _, n := range names {
		rows = append(rows, []string{"`" + n + "`", "`" + filepath.ToSlash(PathFor(n)) + "`"})
	}
	doc.Table([]string{"Test name", "Document path"}, rows...)
}

func TestCheck(t *testing.T) {
	t.Parallel()

	build := func(tb testing.TB, path string, update bool, body string) *Doc {
		d := New(tb, "Title", "Summary.", WithPath(path), withUpdate(update))
		d.Text(body)
		return d
	}

	t.Run("update writes the file", func(t *testing.T) {
		t.Parallel()
		path := filepath.Join(t.TempDir(), "nested", "doc.md")
		tb := newFakeTB(t, "TestX/sub")
		build(tb, path, true, "Hello.")
		tb.finish()
		require.Empty(t, tb.errors)

		got, err := os.ReadFile(path)
		require.NoError(t, err)
		require.Equal(t, "<!-- Generated by TestX/sub using markdiff. Do not edit; rerun the test with -markdiff.update. -->\n\n# Title\n\nSummary.\n\nHello.\n", string(got))
	})

	t.Run("matching file passes", func(t *testing.T) {
		t.Parallel()
		path := filepath.Join(t.TempDir(), "doc.md")
		tb := newFakeTB(t, "TestX")
		build(tb, path, true, "Hello.")
		tb.finish()

		tb = newFakeTB(t, "TestX")
		build(tb, path, false, "Hello.")
		tb.finish()
		require.Empty(t, tb.errors)
	})

	t.Run("mismatch fails with a diff", func(t *testing.T) {
		t.Parallel()
		path := filepath.Join(t.TempDir(), "doc.md")
		tb := newFakeTB(t, "TestX")
		build(tb, path, true, "Hello.")
		tb.finish()

		tb = newFakeTB(t, "TestX")
		build(tb, path, false, "Goodbye.")
		tb.finish()
		require.Len(t, tb.errors, 1)
		require.Contains(t, tb.errors[0], "-Hello.")
		require.Contains(t, tb.errors[0], "+Goodbye.")
		require.Contains(t, tb.errors[0], "-markdiff.update")

		// The checked-in file must not change without update mode.
		got, err := os.ReadFile(path)
		require.NoError(t, err)
		require.Contains(t, string(got), "Hello.")
	})

	t.Run("missing file fails", func(t *testing.T) {
		t.Parallel()
		path := filepath.Join(t.TempDir(), "doc.md")
		tb := newFakeTB(t, "TestX")
		build(tb, path, false, "Hello.")
		tb.finish()
		require.Len(t, tb.errors, 1)
		require.Contains(t, tb.errors[0], "does not exist")
	})

	t.Run("failed tests are not written", func(t *testing.T) {
		t.Parallel()
		path := filepath.Join(t.TempDir(), "doc.md")
		tb := newFakeTB(t, "TestX")
		build(tb, path, true, "Hello.")
		tb.Errorf("unrelated failure")
		tb.finish()
		require.NoFileExists(t, path)
		require.Len(t, tb.logs, 1)
	})

	t.Run("summaries are required", func(t *testing.T) {
		t.Parallel()
		tb := newFakeTB(t, "TestX")
		d := New(tb, "Title", " ", WithPath(filepath.Join(t.TempDir(), "doc.md")))
		d.Section("Behavior", "")
		require.Len(t, tb.fatals, 2)
		require.True(t, strings.Contains(tb.fatals[0], "summary"))
		require.True(t, strings.Contains(tb.fatals[1], "summary"))
	})

	t.Run("paths cannot be shared", func(t *testing.T) {
		t.Parallel()
		path := filepath.Join(t.TempDir(), "doc.md")
		tb := newFakeTB(t, "TestX")
		build(tb, path, true, "One.")
		other := newFakeTB(t, "TestY")
		New(other, "Title", "Summary.", WithPath(path))
		require.Len(t, other.fatals, 1)
		require.Contains(t, other.fatals[0], "TestX")

		// Once the first test finishes, the path can be reused, which
		// allows -count=N runs.
		tb.finish()
		again := newFakeTB(t, "TestX")
		build(again, path, false, "One.")
		again.finish()
		require.Empty(t, again.errors)
		require.Empty(t, again.fatals)
	})
}
