package cmd

import (
	"database/sql"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/charmbracelet/crush/internal/config"
	"github.com/charmbracelet/crush/internal/db"
	"github.com/charmbracelet/crush/internal/message"
	"github.com/spf13/cobra"
)

var exportCmd = &cobra.Command{
	Use:   "export <session-id> [output-file]",
	Short: "Export a conversation to a markdown file",
	Long:  "Export a conversation to a shareable markdown file. Outputs to stdout by default, or to a file if an output path is given.",
	Args:  cobra.RangeArgs(1, 2),
	RunE:  runExport,
}

func runExport(cmd *cobra.Command, args []string) error {
	sessionID := args[0]

	dataDir, _ := cmd.Flags().GetString("data-dir")
	ctx := cmd.Context()

	if dataDir == "" {
		cfg, err := config.Init("", "", false)
		if err != nil {
			return fmt.Errorf("failed to initialize config: %w", err)
		}
		dataDir = cfg.Options.DataDirectory
	}

	conn, err := db.Connect(ctx, dataDir)
	if err != nil {
		return fmt.Errorf("failed to connect to database: %w", err)
	}
	defer conn.Close()

	queries := db.New(conn)

	sess, err := queries.GetSessionByID(ctx, sessionID)
	if err != nil {
		if err == sql.ErrNoRows {
			return fmt.Errorf("session %q not found", sessionID)
		}
		return fmt.Errorf("failed to get session: %w", err)
	}

	msgs, err := queries.ListMessagesBySession(ctx, sessionID)
	if err != nil {
		return fmt.Errorf("failed to list messages: %w", err)
	}

	md, err := renderMarkdown(sess, msgs)
	if err != nil {
		return fmt.Errorf("failed to render markdown: %w", err)
	}

	if len(args) == 2 {
		outputPath := args[1]
		if err := os.WriteFile(outputPath, []byte(md), 0o644); err != nil {
			return fmt.Errorf("failed to write file: %w", err)
		}
		fmt.Fprintf(cmd.ErrOrStderr(), "Exported to %s\n", outputPath)
		return nil
	}

	_, err = fmt.Fprint(cmd.OutOrStdout(), md)
	return err
}

func renderMarkdown(sess db.Session, msgs []db.Message) (string, error) {
	var sb strings.Builder

	createdAt := time.Unix(sess.CreatedAt, 0)

	title := sess.Title
	if title == "" {
		title = "Untitled conversation"
	}

	sb.WriteString("# ")
	sb.WriteString(title)
	sb.WriteString("\n\n")
	sb.WriteString("_Generated by [crush](https://github.com/charmbracelet/crush) on ")
	sb.WriteString(createdAt.Format("January 2, 2006"))
	sb.WriteString("_\n\n")
	sb.WriteString("---\n\n")

	for _, dbMsg := range msgs {
		parts, err := message.UnmarshalParts([]byte(dbMsg.Parts))
		if err != nil {
			return "", fmt.Errorf("failed to unmarshal message parts: %w", err)
		}

		role := message.MessageRole(dbMsg.Role)

		switch role {
		case message.User:
			sb.WriteString("## 👤 User\n\n")
			writeMessageParts(&sb, parts, false)
		case message.Assistant:
			sb.WriteString("## 🤖 Assistant\n\n")
			writeMessageParts(&sb, parts, true)
		case message.Tool:
			// Tool result messages are included inline with assistant messages.
		case message.System:
			// Skip system messages — not useful for sharing.
		}
	}

	return sb.String(), nil
}

func writeMessageParts(sb *strings.Builder, parts []message.ContentPart, isAssistant bool) {
	for _, part := range parts {
		switch p := part.(type) {
		case message.TextContent:
			if text := strings.TrimSpace(p.Text); text != "" {
				sb.WriteString(text)
				sb.WriteString("\n\n")
			}
		case message.ReasoningContent:
			if thinking := strings.TrimSpace(p.Thinking); thinking != "" {
				sb.WriteString("<details>\n<summary>Reasoning</summary>\n\n")
				sb.WriteString(thinking)
				sb.WriteString("\n\n</details>\n\n")
			}
		case message.ToolCall:
			if !isAssistant {
				break
			}
			sb.WriteString("<details>\n<summary>🔧 Tool call: <code>")
			sb.WriteString(p.Name)
			sb.WriteString("</code></summary>\n\n")
			if input := strings.TrimSpace(p.Input); input != "" {
				sb.WriteString("```json\n")
				sb.WriteString(input)
				sb.WriteString("\n```\n\n")
			}
			sb.WriteString("</details>\n\n")
		case message.ToolResult:
			sb.WriteString("<details>\n<summary>🔧 Tool result: <code>")
			sb.WriteString(p.Name)
			sb.WriteString("</code></summary>\n\n")
			if content := strings.TrimSpace(p.Content); content != "" {
				sb.WriteString("```\n")
				sb.WriteString(content)
				sb.WriteString("\n```\n\n")
			}
			sb.WriteString("</details>\n\n")
		case message.Finish:
			// Skip finish parts.
		}
	}
}
