// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permission_rules.sql

package db

import (
	"context"
)

const createPermissionRule = `-- name: CreatePermissionRule :exec
INSERT OR IGNORE INTO permission_rules (tool_name, action, path, params)
VALUES (?, ?, ?, ?)
`

type CreatePermissionRuleParams struct {
	ToolName string `json:"tool_name"`
	Action   string `json:"action"`
	Path     string `json:"path"`
	Params   string `json:"params"`
}

func (q *Queries) CreatePermissionRule(ctx context.Context, arg CreatePermissionRuleParams) error {
	_, err := q.exec(ctx, q.createPermissionRuleStmt, createPermissionRule,
		arg.ToolName,
		arg.Action,
		arg.Path,
		arg.Params,
	)
	return err
}

const deletePermissionRule = `-- name: DeletePermissionRule :exec
DELETE FROM permission_rules WHERE id = ?
`

func (q *Queries) DeletePermissionRule(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deletePermissionRuleStmt, deletePermissionRule, id)
	return err
}

const listPermissionRules = `-- name: ListPermissionRules :many
SELECT id, tool_name, "action", path, created_at, params FROM permission_rules ORDER BY created_at DESC
`

func (q *Queries) ListPermissionRules(ctx context.Context) ([]PermissionRule, error) {
	rows, err := q.query(ctx, q.listPermissionRulesStmt, listPermissionRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionRule{}
	for rows.Next() {
		var i PermissionRule
		if err := rows.Scan(
			&i.ID,
			&i.ToolName,
			&i.Action,
			&i.Path,
			&i.CreatedAt,
			&i.Params,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchPermissionRule = `-- name: MatchPermissionRule :one
SELECT id FROM permission_rules
WHERE tool_name = ? AND action = ? AND path = ?
LIMIT 1
`

type MatchPermissionRuleParams struct {
	ToolName string `json:"tool_name"`
	Action   string `json:"action"`
	Path     string `json:"path"`
}

func (q *Queries) MatchPermissionRule(ctx context.Context, arg MatchPermissionRuleParams) (int64, error) {
	row := q.queryRow(ctx, q.matchPermissionRuleStmt, matchPermissionRule, arg.ToolName, arg.Action, arg.Path)
	var id int64
	err := row.Scan(&id)
	return id, err
}
